name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check project structure
        run: |
          pwd
          ls -la
          find . -name pubspec.yaml
        
      - name: Build Android bundle
        uses: AcmeSoftwareLLC/flutter-build@v2
        with:
          flutter-version: "3.47.2"
          script: flutter build apk --release
