name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Android
        uses: AcmeSoftwareLLC/flutter-build@v2
        with:
          flutter-version: "3.47.2"
          script: flutter build apk --release
